### ISSUE TITLE
Add libstatgrab-dev package

### ISSUE THREAD

**Issue by adamflott** [rust-lang/crates-build-env#109]
**Affected crates:** libstatgrab-sys
**Ubuntu 20.04 packages to install:** libstatgrab-dev

https://docs.rs/crate/libstatgrab-sys/0.2.0/builds/633666

**Comment by syphar** [comment]
@adamflott if you want to quicken the process, could you create a PR for this? 

For an example see 406ce2bfa40eb89667e608d2697b93a622946735

**Comment by syphar** [comment]
I deployed the new image and queued a rebuild of the release

**Comment by adamflott** [comment]
Thanks @syphar ! Appreciate the fast turnaround
