### ISSUE TITLE
FFI upgrade golang version to >= 1.19

### ISSUE THREAD

**Issue by neonphog** [rust-lang/crates-build-env#119]
https://docs.rs/crate/tx5-go-pion-sys/0.0.1-alpha.1/builds/723243

```
[INFO] [stderr]   thread 'main' panicked at 'go executable version must be >= 1.19, got: 1.13', build.rs:42:5
```

**Comment by neonphog** [comment]
Why is ubuntu's golang so old? Would it be possible to switch to jammy? That at least has 1.17 ([https://packages.ubuntu.com/jammy/golang-1.17](https://packages.ubuntu.com/jammy/golang-1.17)] I might be able to pair back the deps that far.

**Comment by syphar** [comment]
We're tracking ubuntu LTS for these images. 

A upgrade to jammy is possible, but is some work (see also #119). 

I'm happy to review a PR :)

**Comment by neonphog** [comment]
I assume you meant see also [#84](https://github.com/rust-lang/crates-build-env/issues/84). Awesome I'll spend a little time on that today.

**Comment by syphar** [comment]
oh yeah, you're right :)

**Comment by syphar** [comment]
I assume the golang version is now up-to-date with the new image (#120) and will close this issue. 

Thank you!

**Comment by neonphog** [comment]
Yep, build env is now up to go 1.18, and I was able to reduce the requirement down to 1.18. Thanks for your help!

**Comment by syphar** [comment]
Thank you for yours!
