### ISSUE TITLE
Docs.rs failed to build doc for sherpa-rs

### ISSUE THREAD

**Issue by thewh1teagle** [rust-lang/crates-build-env#160]
### Problem

Hi,
I'm working on Rust crate in https://github.com/thewh1teagle/sherpa-rs.
I just released new version to crates.io, but it doesn't available in docs.rs.
It says that there was a problem when trying to build the doc. though, the build of docs with `cargo doc` works locally.

The log from docs.rs:
https://docs.rs/crate/sherpa-rs/0.1.9/builds/1317779

Note that the crate `sherpa-rs` depends on `sherpa-rs-sys` which also depends on `sherpa-onnx` submodule.
My assumption is that it doesn't run `git submodule update --init` before building the doc and the `sys` crate failed to build, or because it doesn't have CMake installed.

### Steps

1. Publish new version of `sherpa-rs`
2. Wait for docs.rs to be generated

### Version

cargo 1.79.0 (ffa9cf99a 2024-06-03)
release: 1.79.0
commit-hash: ffa9cf99a594e59032757403d4c780b46dc2c43a
commit-date: 2024-06-03
host: aarch64-apple-darwin
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0 (sys:0.4.72+curl-8.6.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.5.0 [64-bit]

**Comment by syphar** [comment]
> My assumption is that it doesn't run git submodule update --init before building the doc and the sys crate failed to build, 

Docs.rs doesn't use git at all, we just use the source archive that is uploaded to crates.io. If files are missing in the archive that belong to your crate or the `-sys` one, it's a problem in the publishing process of that crate. 

> or because it doesn't have CMake installed.

Please see https://docs.rs/about/builds 

the container we use for building is defined here:  https://github.com/rust-lang/crates-build-env and includes cmake: https://github.com/rust-lang/crates-build-env/blob/b1985bec6dbb979888479019a75953fb3eb4dc50/linux/packages.txt#L16

**Comment by syphar** [comment]
Sorry, I just realized this issue is not on the docs.rs repo, but already the crates-build env. 

Both points still stand. Missing files are a sign of them missing in the release artifact / package, and we _do_ have cmake in our build environment.

**Comment by thewh1teagle** [comment]
Do you have any idea why it failed or how I can investigate further? 
I wasn't sure where to report the issue, I think it would be helpful if docs.rs included information on where to submit error reports.

**Comment by syphar** [comment]
I'm not sure how docs.rs can help here, the variety of potential errors is quite high, and where to post them. 

A good starting point is the repo of the crate itself, it's more likely something is broken there, compared to an issue with docs.rs. 

In this specific case I'm quite sure that that's the right place, since a file is missing that the compilation needs.

**Comment by thewh1teagle** [comment]
> A good starting point is the repo of the crate itself

As the creator of the crate, I can confirm that cargo doc works correctly locally, as well as cargo build and cargo publish. Additionally, the publish process runs successfully in [GitHub action](https://github.com/thewh1teagle/sherpa-rs/actions/runs/11345883774/job/31553742079). However, the issue with docs.rs is beyond my control.

**Comment by syphar** [comment]
regarding `-sys` libraries and building them docs.rs is only special in these ways: 

- we are using this docker container to build (crates-build-env), which means you only have packages, headers, cmake version available as given in this image 
- you only can write to cargo `OUT_DIR` 
- we use cross compilation to build non-linux targets 

You can use the docker container yourself to try building locally, though the setup for this is a little complex ( https://docs.rs/about/builds#diagnosing-failed-builds -> https://forge.rust-lang.org/docs-rs/add-dependencies.html )

There are many many crates with system dependencies whos builds run fine, I recommend checking what they do differently, currently I don't see how our build environment would have to precicely change to support your build semantics. That being said, my only experience with rust crates & system dependencies comes from the years of supporting crate authors here, and no crates of my own, so I can't help with cmake / c / c++ build specifics.
