### ISSUE TITLE
Missing dependency request: libgmsh

### ISSUE THREAD

**Issue by mxxo** [rust-lang/crates-build-env#19]
Hello, 

I am writing a Rust wrapper around the Gmsh SDK, a tool used for CAD and mesh generation. 
http://gmsh.info/

Documentation builds fail since the `libgmsh` library isn't installed by default:
https://docs.rs/crate/gmsh-sys/0.1.0/builds/186306

I believe this image is based on Stretch, but `libgmsh` only started exposing this stable API after version 4, and I think the Stretch version won't work since it's too old (v2.15)

In Buster, this library is here: https://packages.debian.org/buster/libgmsh4.1

Would it be possible to include a compatible `libgmsh` version in this container? 

Thank you very much for your time. 

Max Orok

**Comment by pietroalbini** [comment]
There was actually an error in the README, the image is based on Ubuntu 18.04 LTS (fixed it). Unfortunately it seems like [Gmsh 4.1 is not present on Ubuntu 18.04](https://packages.ubuntu.com/search?keywords=libgmsh), so we can't easily install it in the image. I'm keeping this issue open so we can add it when Ubuntu 20.04 comes out.

**Comment by mxxo** [comment]
Right, thank you very much your quick reply.

**Comment by mxxo** [comment]
The docs.rs builds starting working a couple of months ago and I don't think it was a change on my end. 
https://docs.rs/gmsh-sys/0.1.2/gmsh_sys/
https://docs.rs/rgmsh/0.1.2/rgmsh/

**Comment by jyn514** [comment]
Strange, I don't think we added that package (https://github.com/rust-lang/crates-build-env/commits/master) ... But if the build is working I guess there's no reason to keep this open.
