### ISSUE TITLE
Missing dependency request: libelektra

### ISSUE THREAD

**Issue by PhilippGackstatter** [rust-lang/crates-build-env#21]
Can you add `libelektra-dev` to the system dependencies?

This is for the Rust bindings for [libelektra](https://github.com/ElektraInitiative/libelektra), specifically for the [elektra](https://crates.io/crates/elektra) and [elektra-sys](https://crates.io/crates/elektra-sys) crates. `elektra-sys` uses `rust-bindgen` to generate the bindings from the header file in the above mentioned package. If it's not present then documentation for the `elektra` crate won't build.

I ran the docker image as suggested in the [blog post](https://blog.rust-lang.org/2019/09/18/upcoming-docsrs-changes.html) and installed the package. The documentation then built sucessfully.

Thanks!

**Comment by pietroalbini** [comment]
Thanks! Opened a PR to add that package to the Docker image!

As docs.rs still uses the legacy build environment, I installed the package there as well and rebuilt the docs for [`elektra`](https://docs.rs/elektra/0.9.0/elektra/) and [`elektra-sys`](https://docs.rs/elektra-sys/0.9.0/elektra_sys/). They should be available now.

**Comment by PhilippGackstatter** [comment]
Thank you so much!
