### ISSUE TITLE
Missing dependency request: nettle 3.4.1

### ISSUE THREAD

**Issue by teythoon** [rust-lang/crates-build-env#32]
Unfortunately, the version of the Nettle cryptographic library shipped with Ubuntu 18.04 is too old (3.4) to build our Nettle bindings:

https://docs.rs/crate/nettle/6.0.0/builds/220957

We require at least version 3.4.1.  The oldest Ubuntu release that ships that version is 19.04:

https://packages.ubuntu.com/disco/libnettle6

As an alternative, Debian 10 also ships 3.4.1:

https://packages.debian.org/buster/libnettle6

**Comment by jyn514** [comment]
19.04 is not an LTS release. When 20.04 comes out in a couple months, we could upgrade to that.

I'm reluctant to switch to Debian because their release cycle is much slow than Ubuntu, we'd end up having to switch back if we wanted to stay up to date.

In the meantime, is there something specific you need in 3.4.1? Is it possible to add backwards compatibility with 3.4.0?

@pietroalbini can you transfer to crates-build-env?

**Comment by jyn514** [comment]
Whoops, this is crates-build-env!

**Comment by teythoon** [comment]
> 19.04 is not an LTS release. When 20.04 comes out in a couple months, we could upgrade to that.
>
> I'm reluctant to switch to Debian because their release cycle is much slow than Ubuntu, we'd end up having to switch back if we wanted to stay up to date.

Slightly off-topic, but Debian has put out a stable release every two years since 2005, i.e. it has the same cadence as Ubuntu LTS:

https://wiki.debian.org/DebianReleases

> In the meantime, is there something specific you need in 3.4.1?

rsa_sec_decrypt

> Is it possible to add backwards compatibility with 3.4.0?

I don't know.  We would either have to detect the version of nettle, or detect the presence of a symbol in nettle-sys, and make the compilation of nettle-rs dependent on that.  I don't know how to do either, and to be honest, I would prefer not to do that.  If we were to implement a compile time switch like that, then users of nettle-rs would have no way to know what the properties of the underlying RSA operations are.

**Comment by jyn514** [comment]
> Slightly off-topic, but Debian has put out a stable release every two years since 2005, i.e. it has the same cadence as Ubuntu LTS

Looks like I should have done my research! Thanks for letting me know. I think the point still stands though that if we switched to Debian someone would ask in couple months to switch to Ubuntu 20.04 for more recent packages. With that in mind, I don't think the switch is worth it.

**Comment by jyn514** [comment]
@teythoon since #43 we have nettle 3.5.1 installed. I rebuilt https://docs.rs/crate/nettle/6.0.0 and the docs are now there.

**Comment by jyn514** [comment]
Looks like you published 7.0.0 since this issue was opened, I rebuilt that too.
