### ISSUE TITLE
CI Builds fail on Azure Pipelines since 2020-03-23

### ISSUE THREAD

**Issue by skeleten** [rust-lang/crates-build-env#40]
It seems the action using Azure Pipelines is failing because

```
An image label with the label win1803 does not exist.
```

Earlier faillure gave the more verbose message

```
This job was blocked because it uses a Microsoft hosted agent (win1803) that was removed on March 23rd, 2020.  See https://aka.ms/blocked-hosted-agent for more information.
```

**Comment by jyn514** [comment]
We probably should just remove the Azure CI run, I don't think anyone uses the windows build env (?)

cc @pietroalbini

**Comment by pietroalbini** [comment]
It was used by Crater for Windows. I think for now it's safe to disable it, but we might want to bring it up again if work on it starts back (cc @rylev).
