### ISSUE TITLE
Install libvpx

### ISSUE THREAD

**Issue by astraw** [rust-lang/crates-build-env#82]
**Affected crates:** libvpx-native-sys, env-libvpx-sys, vpx-encode, encode-webm-video-frames
**Ubuntu 20.04 packages to install:** libvpx-dev

**Comment by jyn514** [comment]
@astraw are you interested in making a PR for this? It would get merged faster if you did. https://forge.rust-lang.org/docs-rs/add-dependencies.html

**Comment by astraw** [comment]
PR in https://github.com/rust-lang/crates-build-env/pull/83
