### ISSUE TITLE
libopencv-dev

### ISSUE THREAD

**Issue by eadf** [rust-lang/crates-build-env#90]
[opencv](https://crates.io/crates/opencv/) and all the crates using it could use `libopencv-dev` to make DocTest work.

**Affected crates:** opencv, realsense-rust, rust_drone_follow, abow, cv-convert, nokhwa, podo-std-eye, eorst, printimg, arc_lib, checkerboard, dlib-face-recognition-cv, f-trak, tangram-vision-sdk, softmount, shutter and my own [libstacker](https://crates.io/crates/libstacker)

~~They also needs `clang` and `libclang-dev` but I assume those packages are already installed.~~ already installed.

Failed build [log.](https://docs.rs/crate/libstacker/0.0.2/builds/456134)
**Ubuntu 20.04 packages to install:** libopencv-dev

**Comment by jyn514** [comment]
Hi @eadf, are you interested in making a PR adding that package? It would get merged quicker if so :)

**Comment by eadf** [comment]
I could edit the list and make a PR, but I'm not experienced with docker. Don't know if I could get a test env up to properly test the changes I make.

**Comment by jyn514** [comment]
> Don't know if I could get a test env up to properly test the changes I make.

No worries, that's what CI is for :)

**Comment by eadf** [comment]
We are still having problems with `docs.rs` failing to build the [opencv](https://crates.io/crates/opencv) crate. 

Here is an example of a [recent docs.rs build log](https://docs.rs/crate/libstacker/0.0.4/builds/457715). 

When running the current `linux` docker image locally it can build and test the opencv crate w/o any problems.
So I'm wondering if the `libopencv-dev` patch is live yet? Or, maybe the change needs to be applied to `linux-micro` too?
