### ISSUE TITLE
webview2-com requires Mono for cross compilation

### ISSUE THREAD

**Issue by lucasfernog** [rust-lang/crates-build-env#98]
**Affected crates:** tauri
**Ubuntu 20.04 packages to install:** mono-complete (requires adding an HTTPS repository)

The `tauri` crate uses [webview2-com](https://github.com/wravery/webview2-rs) and it needs [mono](https://www.mono-project.com/download/stable/#download-lin) to [cross compile](https://github.com/wravery/webview2-rs#cross-compilation). I wanted to make a PR for this but since it involves adding a new repository, I wanted to check the policy and if you would allow that.

**Comment by syphar** [comment]
In the readme I see: 
> Note that the package needs to be available in the Ubuntu 20.04 archives.

So adding a new repository won't be possible (please correct me if I'm wrong @jyn514 ) 

Coming back to the original issue (https://github.com/rust-lang/docs.rs/issues/1679) : 
The readme for cross-compilation of `webview2-com` also says: 
> The webview2-com-sys [build.rs](https://github.com/wravery/webview2-rs/blob/main/crates/bindings/build.rs) script automatically downloads and extracts the NuGet package for the SDK and links against the libraries from that package.

Which implies that the crate needs network access for the build. 

I don't know much about the crates themselves, but in the [webview2-com-sys Cargo.toml](https://github.com/wravery/webview2-rs/blob/main/crates/bindings/Cargo.toml#L11-L19) you see that there is a `nuget` feature that is disabled for the docs.rs build. 

So your way to go might also be to disable this feature in the docs.rs build, so the docs are fine. This assumes that your crate compiles without the `nuget` feature being active.

**Comment by lucasfernog** [comment]
Thanks for catching that, I'll see what I can do. :heart:
